version: '3' # Version of YML file

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test1234
    networks:
      custom_network:
        #ipv4_address: 10.20.0.1

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: test1234
    networks:
      custom_network:
        #ipv4_address: 10.20.0.2

volumes:
  db_data: {}

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16

